- name: Editing neutron.conf file
  copy:
    src: neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0640'
  when: ansible_distribution == "CentOS"

- name: Editing ml2_conf.ini file
  copy:
    src: ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: '0640'
  when: ansible_distribution == "CentOS"

- name: Editing linuxbridge_agent.ini file
  copy:
    src: linuxbridge_agent.ini 
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
    owner: root
    group: neutron
    mode: '0640'
  when: ansible_distribution == "CentOS"

- name: Editing dhcp_agent.ini file
  copy:
    src: dhcp_agent.ini
    dest: /etc/neutron/dhcp_agent.ini
    owner: root
    group: neutron
    mode: '0640'
  when: ansible_distribution == "CentOS"

